### ISSUE TITLE
Rendering SVG Images Breaks in SVGLIB 0.9.0. Works Fine in 0.8.1.

### ISSUE THREAD

**Issue by louis-gallo-cigna** [deeplook/svglib#170] opened 2018-12-25 18:49 UTC
I notice that my rendering of SVG images into a PDF breaks when running svglib 0.9.0. It will take my color SVG chart images and render them into really bad black and white chart images in the PDF. If I downgrade to svglib 0.8.1, everything is fine. 

    from reportlab.graphics import renderPDF
    from reportlab.pdfgen import canvas
    from svglib.svglib import svg2rlg
    #
    strMyTestSVGFile = "test.svg"
    my_canvas = canvas.Canvas("test.pdf")
    #
    drawing = svg2rlg(strMyTestSVGFile)
    #
    renderPDF.draw(drawing, my_canvas, 0,0)
    my_canvas.save()

Thanks,

Lou

**Comment by louis-gallo-cigna** [comment] 2018-12-27 17:34
Apologies, Deeplook. I have to get permission to upload the files from our Security folks. I will have these files uploaded shortly.

**Comment by deeplook** [comment] 2019-01-10 11:38
I'm closing this due to lack of further info. Please feel free to reopen when more info is available.

**Comment by louis-gallo-cigna** [comment] 2019-01-10 13:36
Sorry, I am not good with Github yet. The test files with both old and new version are attached.

[SVGLIB-0.8.1-NO-BUG-12242018-0000-to-12242018-1030-TEST-1.pdf](https://github.com/deeplook/svglib/files/2745491/SVGLIB-0.8.1-NO-BUG-12242018-0000-to-12242018-1030-TEST-1.pdf)
[SVGLIB-0.9.0-WITH-BUG-12242018-0000-to-12242018-1030-TEST-1.pdf](https://github.com/deeplook/svglib/files/2745492/SVGLIB-0.9.0-WITH-BUG-12242018-0000-to-12242018-1030-TEST-1.pdf)

Thanks,

Lou

**Comment by deeplook** [comment] 2019-01-10 14:14
@louis-gallo-cigna What I want is a minimal piece of code that reproduces a would-be bug.

**Comment by claudep** [comment] 2019-01-10 14:57
What's even more important is the SVG source. But yes, the smaller the example is the better.

**Comment by deeplook** [comment] 2019-01-15 12:45
Putting this on hold until more information is available.

**Closed by deeplook** 2019-01-15 12:45 UTC
