### ISSUE TITLE
font-family not handled properly?

### ISSUE THREAD

**Issue by htgoebel** [deeplook/svglib#89] opened 2017-06-04 14:21 UTC
The example document uses the fonts "Dingbats", "Verdana", "serif", "Times-Roman" and "Helvetica". In the generated PDF I can only find "/Times-Roman" (may be a correct substitute for "serif") and "Helvetica".

1. "serif" seems to be handle properly, see second line ("Zeile 3")
2. "Times-Roman" and "Helvetica seem to be handled properly, see second text-block: Times (green) renders differently than Helvetica (black).
3. "Dingbats" is ignored, see fist line (blue).
4. "Verdana" is ignored, see last block: The text using Helvetica (black) is printed at the same position as the second one using Verdana (red). While Verdana is different from Helvetica, the text is rendering the same, as you can see.

``` xml
<?xml version="1.0" standalone="no"?>
<svg width="210mm" height="297mm"
     xmlns="http://www.w3.org/2000/svg" version="2">
<text x="5cm" y="10cm" xml:space="preserve"
      font-family="Dingbats" font-size="32" fill="blue"><tspan/>
<tspan>Hello, out </tspan>
<tspan font-weight="bold" fill="red">not</tspan><tspan> there!</tspan>
<tspan font-family="serif" x="5cm" dy="32">Zeile 3 iIlL</tspan>
  </text>

<text x="5cm" y="13cm"
      font-family="Times-Roman" font-size="32" fill="lightgreen">
2. Hello, out not there!</text>
<text x="5cm" y="13cm"
      font-family="Helvetica" font-size="32">
3. Hello, out not there!</text>

<text x="5cm" y="14.5cm"
      font-family="Verdana" font-size="32" fill="red">
4. Hello, out not there!</text>
<text x="5cm" y="14.5cm"
      font-family="Helvetica" font-size="32">
5. Hello, out not there!</text>

</svg>
```

![grafik](https://cloud.githubusercontent.com/assets/784161/26762393/a91174ee-4941-11e7-9227-818884f44761.png)

**Comment by deeplook** [comment] 2017-06-05 06:48
I don't think there was a lot of test effort regarding fonts. The way reportlab works (from my ancient knowledge about it) regarding PDF output is that the "standard 14 Postscript" fonts are included/available into every PDF file, while any other needs to be declared and embedded manually, e.g. as TrueType or Type-1. Verdana is not one of the 14 standard ones, see: http://www.enfocus.com/manuals/ReferenceGuide/PP/10/enUS/en-us/concept/c_aa1140975.html

**Comment by claudep** [comment] 2018-03-02 09:09
To embed fonts in PDF, we'll have to obtain the font system path. It looks like Python doesn't offer a simple way to get OS-independent system font files. The best implementation I found until now is matplotlib font_manager (https://matplotlib.org/api/font_manager_api.html). Requiring matplotlib is a bit of a heavy dependency, but we might optionally depend on it for better font support?

**Comment by claudep** [comment] 2018-03-02 09:10
See #107 for a similar issue with a Chinese font.

**Comment by deeplook** [comment] 2018-03-04 15:24
Better font support would certainly be a nice-to-have essential feature. But I'd rather include some existing code from elsewhere doing font search than add a dependency on something as huge as matplotlib. The easiest to start with would be to ask the svglib user to provide a list of directories to find fonts in.

**Comment by claudep** [comment] 2018-03-04 18:28
Agreed. My patch above is a first step to better support the standard PDF fonts. Then we can gradually improve support for other fonts.

**Comment by claudep** [comment] 2018-03-09 09:38
Would be great if you could test again the result with the more recent svglib code.

**Comment by htgoebel** [comment] 2018-03-10 17:39
On my system, at least "Verdana" is no longer "Helvetica". (Curiously it is DejaVuSans, Verdana is not installed on my system).
The text in Dingbats is now gives:
> Unable to find a suitable font for 'Dingbats'

**Comment by claudep** [comment] 2018-03-11 08:15
If the font is not installed on your system and Fontconfig is available, the used font will be indeed the Fontconfig default, which is `DejaVuSans` on many Linux systems. WOUld you suggest some other behavior?

> Unable to find a suitable font for 'Dingbats'

Note that the font name in the standard fonts is `ZapfDingbats`. Do you have a `Dingbats` font installed on your system?

**Comment by claudep** [comment] 2019-05-18 12:34
Font support has improved a lot since this issue was reported. I'm closing this issue, suggesting that specific font bugs to be created as separate issues with detailed reproducing instructions.

**Closed by claudep** 2019-05-18 12:34 UTC
Labels: backlog
