### ISSUE TITLE
chinese chars rendering

### ISSUE THREAD

**Issue by yjf0824** [deeplook/svglib#107] opened 2018-03-02 01:07 UTC
@deeplook , my svg include chinese charset. after use renderPM.drawToFile(drawing, "/home/xxx.png"),
 the messy code appears like:
![image](https://user-images.githubusercontent.com/13815306/36839580-6b365bb0-1d7d-11e8-8242-e4f2b88605f9.png)
How can I solve the messy code problem? Thanks for your apply.

my svg is:

<svg version="1.1" class="highcharts-root" style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="752" viewBox="0 0 752 229" height="229"><desc>Created with Highcharts 5.0.3</desc><defs><clipPath id="highcharts-hyliza3-7-clone"><rect x="0" y="0" width="649" height="158" fill="none"></rect></clipPath></defs><rect fill="#fff" class="highcharts-background" x="0" y="0" width="752" height="229" rx="0" ry="0"></rect><rect fill="none" class="highcharts-plot-background" x="83" y="10" width="649" height="158"></rect><g class="highcharts-grid highcharts-xaxis-grid "><path fill="none" class="highcharts-grid-line" d="M 120.5 10 L 120.5 168" opacity="1"></path><path fill="none" class="highcharts-grid-line" d="M 332.5 10 L 332.5 168" opacity="1"></path><path fill="none" class="highcharts-grid-line" d="M 544.5 10 L 544.5 168" opacity="1"></path><path fill="none" opacity="1" class="highcharts-grid-line" d="M 226.5 10 L 226.5 168"></path><path fill="none" opacity="1" class="highcharts-grid-line" d="M 438.5 10 L 438.5 168"></path><path fill="none" opacity="1" class="highcharts-grid-line" d="M 651.5 10 L 651.5 168"></path></g><g class="highcharts-grid highcharts-yaxis-grid "><path fill="none" stroke="#cecece" stroke-width="1" class="highcharts-grid-line" d="M 83 168.5 L 732 168.5" opacity="1"></path><path fill="none" stroke="#cecece" stroke-width="1" class="highcharts-grid-line" d="M 83 89.5 L 732 89.5" opacity="1"></path><path fill="none" stroke="#cecece" stroke-width="1" class="highcharts-grid-line" d="M 83 9.5 L 732 9.5" opacity="1"></path></g><rect fill="none" class="highcharts-plot-border" x="83" y="10" width="649" height="158"></rect><g class="highcharts-axis highcharts-xaxis "><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 120.5 168 L 120.5 178" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 332.5 168 L 332.5 178" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 544.5 168 L 544.5 178" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 226.5 168 L 226.5 178" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 438.5 168 L 438.5 178" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#cecece" stroke-width="1" d="M 651.5 168 L 651.5 178" opacity="1"></path><text x="83" text-anchor="start" transform="translate(0,0)" class="highcharts-axis-title" style="color: rgb(85, 85, 85); fill: rgb(85, 85, 85);" y="205">时间</text><path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="1" d="M 83 168.5 L 732 168.5"></path></g><g class="highcharts-axis highcharts-yaxis "><text x="33.65625" text-anchor="middle" transform="translate(0,0) rotate(270 33.65625 89)" class="highcharts-axis-title" style="color: rgb(85, 85, 85); fill: rgb(85, 85, 85);" y="89">bps</text><path fill="none" class="highcharts-axis-line" d="M 83 10 L 83 168"></path></g><g class="highcharts-series-group"><g class="highcharts-series highcharts-series-0 highcharts-column-series highcharts-color-undefined highcharts-tracker" transform="translate(83,10) scale(1 1)" width="158" height="649" clip-path="url(#highcharts-hyliza3-7-clone)"><rect x="9.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="30.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="51.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="73.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="94.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="115.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="136.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="158.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="179.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="200.5" y="31.5" width="14" height="127" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="221.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="242.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="264.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="285.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="306.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="327.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="349.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="370.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="391.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="412.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="433.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="455.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="476.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="497.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="518.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="540.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="561.5" y="31.5" width="14" height="127" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="582.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="603.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect><rect x="624.5" y="32.5" width="14" height="126" fill="#81c008" class="highcharts-point" stroke="#81c008" stroke-width="1"></rect></g><g class="highcharts-markers highcharts-series-0 highcharts-column-series highcharts-color-undefined " transform="translate(83,10) scale(1 1)" width="158" height="649" clip-path="none"></g></g><text x="376" text-anchor="middle" class="highcharts-title" style="color: rgb(85, 85, 85); font-size: 18px; display: none; fill: rgb(85, 85, 85); width: 668px;" y="24"><tspan>比特率 - 时间分布</tspan></text><g class="highcharts-legend" transform="translate(345,210)"><rect fill="none" class="highcharts-legend-box" rx="0" ry="0" x="0" y="0" width="63" height="9" visibility="visible"></rect><g><g><g class="highcharts-legend-item highcharts-column-series highcharts-color-undefined highcharts-series-0" transform="translate(0,-5)"><text x="17" style="color: rgb(85, 85, 85); cursor: pointer; line-height: 12px; font-size: 12px; fill: rgb(85, 85, 85);" text-anchor="start" y="15">总量</text><rect x="0" y="4" width="12" height="12" fill="#81c008" rx="2" ry="2" class="highcharts-point"></rect></g></g></g></g><g class="highcharts-axis-labels highcharts-xaxis-labels "><text x="120.98920863309353" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>14:40</tspan></text><text x="333.21942446043164" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>14:50</tspan></text><text x="545.4496402877699" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>15:00</tspan></text><text x="227.1043165467626" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>14:45</tspan></text><text x="439.3345323741007" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>14:55</tspan></text><text x="651.5647482014388" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 120px; text-overflow: clip;" text-anchor="middle" transform="translate(0,0)" y="187" opacity="1"><tspan>15:05</tspan></text></g><g class="highcharts-axis-labels highcharts-yaxis-labels "><text x="68" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 238px; text-overflow: clip;" text-anchor="end" transform="translate(0,0)" y="173" opacity="1"><tspan>0</tspan></text><text x="68" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 238px; text-overflow: clip;" text-anchor="end" transform="translate(0,0)" y="94" opacity="1"><tspan>200k</tspan></text><text x="68" style="color: rgb(85, 85, 85); cursor: default; font-size: 11px; fill: rgb(85, 85, 85); width: 238px; text-overflow: clip;" text-anchor="end" transform="translate(0,0)" y="15" opacity="1"><tspan>400k</tspan></text></g></svg>

**Comment by claudep** [comment] 2018-03-02 09:02
Now I see we already have the issue #89 about font support. I guess the root cause is the same.

**Comment by claudep** [comment] 2018-03-09 09:37
@yjf0824 with svglib master, there is a bit more chances your fonts display correctly. Could you test?
If it's not the case, could you provide the SVG source, your OS type, and the font file name on your system (if you can find it)?

**Comment by claudep** [comment] 2018-04-03 15:17
Without any feedback from reporter, I assume the issue is fixed in master.

**Closed by claudep** 2018-04-03 15:17 UTC

**Comment by bindai** [comment] 2021-04-09 11:46
@yjf0824  I met the same issue. Could you please share how you fix it? Thank you!

**Comment by bindai** [comment] 2021-04-14 08:07
`from svglib.svglib import svg2rlg, register_font
register_font('SimHei', path + '/static/simhei.ttf')`
