### ISSUE TITLE
ZeroDivisionError when trying to convert SVG to PDF/PNG

### ISSUE THREAD

**Issue by fourjr** [deeplook/svglib#206] opened 2019-07-12 15:01 UTC
[This](https://gist.github.com/fourjr/ab90768916faa5d92cb26c106d598821) is the SVG file that I am trying to convert.

Full error: 
```
C:\Users\admin-pc\AppData\Roaming\Python\Python37\Scripts>python svg2pdf -o "C:\Users\admin-pc\Desktop\test.pdf" "C:\Users\admin-pc\Documents\jr\revvid\premium\revvid\dump\emoji.svg"
Traceback (most recent call last):
  File "svg2pdf", line 131, in <module>
    _main()
    -> <function _main at 0x00000252907FE950>
  File "svg2pdf", line 127, in _main
    svg2pdf(path, outputPat=args.output)
    |       |               -> Namespace(input=['C:\\Users\\admin-pc\\Documents\\jr\\revvid\\premium\\revvid\\dump\\emoji.svg'], output='C:\\Users\\admin-pc\\D...
    |       -> 'C:\\Users\\admin-pc\\Documents\\jr\\revvid\\premium\\revvid\\dump\\emoji.svg'
    -> <function svg2pdf at 0x000002528F41C1E0>
  File "svg2pdf", line 47, in svg2pdf
    renderPDF.drawToFile(drawing, out_path, showBoundary=0)
    |                    |        -> 'C:\\Users\\admin-pc\\Desktop\\test.pdf'
    |                    -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    -> <module 'reportlab.graphics.renderPDF' from 'C:\\Users\\admin-pc\\AppData\\Roaming\\Python\\Python37\\site-packages\\reportlab\\...
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderPDF.py", line 302, in drawToFile
    draw(d, c, 0, 0, showBoundary=showBoundary)
    |    |  |                     -> 0
    |    |  -> <reportlab.pdfgen.canvas.Canvas object at 0x00000252907E00F0>
    |    -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    -> <function draw at 0x000002528FCD6158>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderPDF.py", line 29, in draw
    R.draw(renderScaledDrawing(drawing), canvas, x, y, showBoundary=showBoundary)
    |      |                   |         |       |  |               -> 0
    |      |                   |         |       |  -> 0
    |      |                   |         |       -> 0
    |      |                   |         -> <reportlab.pdfgen.canvas.Canvas object at 0x00000252907E00F0>
    |      |                   -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    |      -> <function renderScaledDrawing at 0x00000252906B39D8>
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderbase.py", line 205, in draw
    self.drawNode(drawing)
    |             -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderPDF.py", line 54, in drawNode
    self.drawNodeDispatcher(node)
    |                       -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderbase.py", line 286, in drawNodeDispatcher
    self.drawGroup(node)
    |              -> <reportlab.graphics.shapes.Drawing object at 0x0000025290710BA8>
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderbase.py", line 317, in drawGroup
    self.drawNode(node)
    |             -> <reportlab.graphics.shapes.Group object at 0x00000252907FB5C0>
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderPDF.py", line 56, in drawNode
    self._tracker.pop()
    -> <reportlab.graphics.renderPDF._PDFRenderer object at 0x00000252907FBD68>
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderbase.py", line 112, in pop
    reverseDelta[key] = inverse(lastDelta['transform'])
    |            |      |       -> {'transform': (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)}
    |            |      -> <function inverse at 0x000002528FCD6488>
    |            -> 'transform'
    -> {}
  File "C:\Users\admin-pc\AppData\Roaming\Python\Python37\site-packages\reportlab\graphics\renderbase.py", line 16, in inverse
    R = [A[3]/det, -A[1]/det, -A[2]/det, A[0]/det]
         |    |     |    |     |    |    |    -> 0.0
         |    |     |    |     |    |    -> (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
         |    |     |    |     |    -> 0.0
         |    |     |    |     -> (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
         |    |     |    -> 0.0
         |    |     -> (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
         |    -> 0.0
         -> (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
ZeroDivisionError: float division by zero
```

I have tried this with code as well with similar results:
```python
data = BytesIO()
drawing = svg2rlg('dump/emoji.svg')
renderPM.drawToFile(drawing, data, fmt="PNG")
```

**Comment by claudep** [comment] 2019-07-12 18:08
Duplicate of #195. Just released 0.9.2 including the fix.

**Closed by claudep** 2019-07-12 18:08 UTC
